-- AñADE UNA COLUMNA DE TIPO ROWVERSION A LA TABLA USUARIOS
ALTER TABLE Usuarios ADD version_fila ROWVERSION;

-- CONSULTA PARA OBTENER LOS VALORES DE LA COLUMNA ROWVERSION
SELECT id_usuario, nombre, version_fila FROM Usuarios

-- ACTUALIZAR UN REGISTRO UTILIZANDO LA COLUMNA ROWVERSION PARA CONTROLAR CONCURRENCIA OPTIMISTA
UPDATE Usuarios
SET nombre = 'Juan Pérez'
WHERE id_usuario = 1 AND version_fila =0x0000000000002711; 
